name: build-packages
on: [push, pull_request]
env:
  LIN: "ubuntu-16.04"
  OSX: "macos-latest"
  WIN: "windows-latest"
defaults:
  run:
    shell: bash
jobs:
  dtc-linux:
    runs-on: ${{ env.LIN }}
    env:
      PACKAGE: "dtc"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  dtc-osx:
    runs-on: ${{ env.OSX }}
    env:
      PACKAGE: "dtc"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  wishbone-tool-linux:
    runs-on: ${{ LIN }}
    env:
      PACKAGE: "wishbone-tool"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  wishbone-tool-osx:
    runs-on: ${{ OSX }}
    env:
      PACKAGE: "wishbone-tool"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  wishbone-tool-windows:
    runs-on: ${{ WIN }}
    env:
      PACKAGE: "wishbone-tool"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  sigrok-cli-linux:
    runs-on: ${{ LIN }}
    env:
      PACKAGE: "sigrok-cli"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  sigrok-cli-osx:
    runs-on: ${{ OSX }}
    env:
      PACKAGE: "sigrok-cli"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  renode-linux:
    runs-on: ${{ LIN }}
    env:
      PACKAGE: "renode"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  renode-osx:
    runs-on: ${{ OSX }}
    env:
      PACKAGE: "renode"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: brew install coreutils
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  renode-windows:
    runs-on: ${{ WIN }}
    env:
      PACKAGE: "renode"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  capnproto-linux:
    runs-on: ${{ LIN }}
    env:
      PACKAGE: "capnproto"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  zachjs-sv2v-linux:
    runs-on: ${{ LIN }}
    env:
      PACKAGE: "zachjs-sv2v"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
  capnproto-java-linux:
    runs-on: ${{ LIN }}
    needs: "capnproto-linux"
    env:
      PACKAGE: "capnproto-java"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@move-to-ghactions
